export REPOS=$HOME/src
export PYENV_ROOT="$HOME/.pyenv"
eval "$(rbenv init -)"
eval "$(pyenv init -)"
source "$HOME/src/liftoff/ops/credentials/developer.profile"
export PATH="$PATH:/Applications/MacVim.app/Contents/bin"
export LIFTOFF_VENV_ROOT=~/.venv
alias li="cd $REPOS/liftoff"
alias sk="li; cd skipper/"
alias bl="li; cd blixem/"
alias h2="li; cd h2go/"
alias ha="li; cd hawker/"
alias pi="cd $REPOS/liftoff/postgres_db/pinpoint && psql pinpoint"
alias rmi="$REPOS/liftoff/postgres_db/script/run_all_migrations.sh"
alias re="cd $REPOS"
alias sr="cd ~/src"
alias mi="sr; cd miscellany"
alias ra="./bin/run_app.sh"
export KAFKA_DIR=$REPOS/kafka
alias gaid="grep -o -E '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}'"
alias idfa="grep -o -E '[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}'"
alias wcl="wc -l"
alias g="git"
alias clt="clj -A:liftoff:dev:test"
alias cls="clj -A:liftoff:dev:test"
alias clr="clj -A:liftoff:dev:nrepl"
alias gt="go test ./..."
alias gtv="gt -v"
alias gb="go build"

export ANDROID_SDK="$HOME/Library/Android/sdk"
export PATH="$ANDROID_SDK/platform-tools:$PATH"
