export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"
source "$HOME/src/liftoff/ops/credentials/developer.profile"
eval "$(rbenv init -)"
alias li="cd $REPOS/liftoff"
alias sk="li; cd skipper/"
alias pi="cd $REPOS/liftoff/postgres_db/pinpoint && psql pinpoint"
alias pin="li; cd pinpoint/"
alias re="cd $REPOS"
alias co="cd ~/src"
alias sr="cd ~/src"
alias mi="co; cd miscellany"
alias an="psql analytics"
alias coh="psql cohort"
alias lipr="vim ~/.liftoff_profile"
alias ra="./bin/run_app.sh"
export KAFKA_DIR=$REPOS/kafka
alias gaid="grep -o -E '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}'"
alias idfa="grep -o -E '[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}'"
